version: '3.8'

services:
  my_postgres:
    image: postgres:15.1
    ports:
      - "5432:5432"
    env_file:
      - db-env-local
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - my_postgres
    environment:
      - DB_HOST=my_postgres
      - DB_PORT=5432
    ports:
      - "8080:8080"
    env_file:
      - app-env-local
    command: [ "./main" ]

volumes:
  postgres_volume: