// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	dto "genesis-currency-api/pkg/dto"

	mock "github.com/stretchr/testify/mock"
)

// CurrencyServiceInterface is an autogenerated mock type for the CurrencyServiceInterface type
type CurrencyServiceInterface struct {
	mock.Mock
}

// GetCurrencyInfo provides a mock function with given fields:
func (_m *CurrencyServiceInterface) GetCurrencyInfo() (dto.CurrencyInfoDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencyInfo")
	}

	var r0 dto.CurrencyInfoDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() (dto.CurrencyInfoDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() dto.CurrencyInfoDTO); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dto.CurrencyInfoDTO)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCurrencyRate provides a mock function with given fields:
func (_m *CurrencyServiceInterface) GetCurrencyRate() (dto.CurrencyResponseDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencyRate")
	}

	var r0 dto.CurrencyResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() (dto.CurrencyResponseDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() dto.CurrencyResponseDTO); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dto.CurrencyResponseDTO)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCurrencyRates provides a mock function with given fields:
func (_m *CurrencyServiceInterface) UpdateCurrencyRates() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdateCurrencyRates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCurrencyServiceInterface creates a new instance of CurrencyServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrencyServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrencyServiceInterface {
	mock := &CurrencyServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
