// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	dto "genesis-currency-api/pkg/dto"

	mock "github.com/stretchr/testify/mock"
)

// CurrencyService is an autogenerated mock type for the CurrencyService type
type CurrencyService struct {
	mock.Mock
}

// GetCurrencyInfo provides a mock function with given fields:
func (_m *CurrencyService) GetCurrencyInfo() dto.CurrencyInfoDTO {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencyInfo")
	}

	var r0 dto.CurrencyInfoDTO
	if rf, ok := ret.Get(0).(func() dto.CurrencyInfoDTO); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dto.CurrencyInfoDTO)
	}

	return r0
}

// GetCurrencyRate provides a mock function with given fields:
func (_m *CurrencyService) GetCurrencyRate() dto.CurrencyResponseDto {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencyRate")
	}

	var r0 dto.CurrencyResponseDto
	if rf, ok := ret.Get(0).(func() dto.CurrencyResponseDto); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dto.CurrencyResponseDto)
	}

	return r0
}

// UpdateCurrencyRates provides a mock function with given fields:
func (_m *CurrencyService) UpdateCurrencyRates() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdateCurrencyRates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCurrencyService creates a new instance of CurrencyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCurrencyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CurrencyService {
	mock := &CurrencyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
