// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailServiceInterface is an autogenerated mock type for the EmailServiceInterface type
type EmailServiceInterface struct {
	mock.Mock
}

// SendEmails provides a mock function with given fields:
func (_m *EmailServiceInterface) SendEmails() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SendEmails")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEmailServiceInterface creates a new instance of EmailServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailServiceInterface {
	mock := &EmailServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
