// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	dto "genesis-currency-api/pkg/dto"

	mock "github.com/stretchr/testify/mock"
)

// UserGetter is an autogenerated mock type for the UserGetter type
type UserGetter struct {
	mock.Mock
}

// GetAll provides a mock function with given fields:
func (_m *UserGetter) GetAll() ([]dto.UserResponseDTO, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []dto.UserResponseDTO
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]dto.UserResponseDTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []dto.UserResponseDTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.UserResponseDTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserGetter creates a new instance of UserGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserGetter {
	mock := &UserGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
